### ISSUE TITLE
Sort by score descending before plotting each team

### ISSUE THREAD

**Issue by shinmichaelao** [woogers/mjgl-tools#4] opened 2021-05-02 03:09 UTC
Currently the legend is sorted by team number which makes it more confusing to figure out which team is which line.

https://github.com/woogers/mjgl-tools/blob/8c37977acd624931751ba98426f6fd172a5e2ad5/go.py#L110

Add the teams in order of score, then the legend will be sorted and easier for reader to understand. (Top line will correspond to top team in the legend)

**Comment by woogers** [comment] 2021-05-02 14:30
Duplicate of #3

**Closed as completed by woogers** 2021-05-02 14:30 UTC
Labels: duplicate
